config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  resources :blog, only: [:index, :show]

  resources :services, only: [:index]

  resources :portfolio, only: [:index, :show]

  resources :contacts, only: [:new ,:create]
  #this is a much better way of serving static pages through the static_pages controller's show action
  get 'static_pages/*page' => 'static_pages#show'


end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :contacts_name, :validate => true
    attribute :contacts_email, :validate => /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/
    attribute :contacts_phone, :validate => true
    attribute :contacts_message, :validate => true
    attribute :nickname, :captcha => true
    def headers
        {
        :subject => "Info from africarlogistics.com",
        :to => "sales@africarlogistics.tours",
        :from => %("#{contacts_name}" <#{contacts_email}>)
        }
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
      @contact = Contact.new
  end

  def create
      @contact = Contact.new(params[:contact])
      @contact.request = request
      if @contact.deliver
          flash.now[:error]= nil
          else
          flash.now[:error]="Cannot send message"
          render :new
      end
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
    if valid_page?
      render template: "static_pages/#{params[:page]}"
    else
      render file: "public/404.html.erb", status: :not_found
    end
  end

  private
  def valid_page?
    File.exist?(Pathname.new(Rails.root + "app/views/static_pages/#{params[:page]}.html.erb"))
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/index.html.erb
<head>

  <!--&lt;!&ndash; font-awesome &ndash;&gt;-->
  <!--<link href="/font-awesome.min.css" rel="stylesheet">-->
  <!--&lt;!&ndash;[if lt IE 9]>-->
  <!--<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>-->
  <!--<![endif]&ndash;&gt;-->
  <!--&lt;!&ndash;[if IE 7]>-->
  <!--<link href="/font-awesome-ie7.css" rel="stylesheet">-->
  <!--<![endif]&ndash;&gt;-->

  <!--&lt;!&ndash; Bootstrap core CSS &ndash;&gt;-->
  <!--<link href="/bootstrap.css" rel="stylesheet">-->

  <!--&lt;!&ndash; custom CSS &ndash;&gt;-->
  <!--<link href="/style.css" rel="stylesheet">-->
  <!--&lt;!&ndash;[if lte IE 8]>-->
  <!--<link href="/ie8.css" rel="stylesheet">-->
  <!--<![endif]&ndash;&gt;-->
  <!--&lt;!&ndash;[if lte IE 7]>-->
  <!--<link href="/ie7.css" rel="stylesheet">-->
  <!--<![endif]&ndash;&gt;-->

  <!--&lt;!&ndash; JavaScript &ndash;&gt;-->
  <!--<script type="text/javascript" src="/jquery-1.10.2.js"></script>-->
  <!--<script type="text/javascript" src="/bootstrap.js"></script>-->
  <!--<script type="text/javascript" src="/plugins.js"></script>-->
  <!--&lt;!&ndash;[if lte IE 7]>-->
  <!--<script type="text/javascript" src="/boxsizing/jquery.boxsizing.js"></script>-->
  <!--<![endif]&ndash;&gt;-->
  <!--<script type="text/javascript" src="/banzhow.js"></script>-->

  <!--<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?"></script>-->
  <script>
      function initMap() {
          var uluru = {lat: 0.351505, lng: 32.604188};
          var map = new google.maps.Map(document.getElementById('map-canvas'), {
              zoom: 4,
              center: uluru
          });
          var marker = new google.maps.Marker({
              position: uluru,
              map: map
          });
      }
  </script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB-VrqUYZwMuDWT0ZXHYcMqRGEjPwQ3tFY&callback=initMap"
          type="text/javascript"></script>


</head>

<%= render 'layouts/navbar'%>

<div id="map-canvas" class="carousel"></div>

<div class="section">

  <div class="container">

    <div class="row">

      <div class="col-sm-8">
        <h3>Contact</h3>
        <p>Please send us a message and we shall get back to you as soon as possible</p>

        <form role="form" method="POST" action="contact-form-submission.php">
          <div class="row">
            <div class="form-group col-md-12">
              <label for="input1">Name</label>
              <input type="text" name="contact_name" class="form-control" id="input1">
            </div>
            <div class="form-group col-md-12">
              <label for="input2">Email Address</label>
              <input type="email" name="contact_email" class="form-control" id="input2">
            </div>
            <div class="form-group col-md-12">
              <label for="input3">Phone Number</label>
              <input type="phone" name="contact_phone" class="form-control" id="input3">
            </div>
            <div class="clearfix"></div>
            <div class="form-group col-lg-12">
              <label for="input4">Message</label>
              <textarea name="contact_message" class="form-control" rows="6" id="input4"></textarea>
            </div>
            <div class="form-group col-lg-12">
              <input type="hidden" name="save" value="contact">
              <button type="submit" class="btn btn-primary pull-right">Submit</button>
              <div class="clearfix"></div>
            </div>
          </div>
        </form>
      </div>

      <div class="col-sm-4">
        <h3>Address</h3>
        <h4>Africarlogistics</h4>
        <p>
          <i class="fa fa-map-marker"></i> 123 Nkurumah Road, Kampala.
        </p>
        <p><i class="fa fa-phone"></i> 0772441442</p>
        <p><i class="fa fa-envelope"></i> <a href="mailto:info@banzhow.com">info@africarlogistics.tours</a></p>
        <p><i class="fa fa-clock-o"></i> Monday - Saturday: 9:00 AM to 5:00 PM</p>
      </div>

    </div><!-- /.row -->

  </div><!-- /.container -->

</div><!-- /.section -->


<%= render 'layouts/footer'%>

<%= render 'layouts/rights'%>

app/views/contact/show.html.erb
<h1>Contact#show</h1>
<p>Find me in app/views/contact/show.html.erb</p>

app/views/contacts/create.html.erb
<%= render 'layouts/navbar'%>
<section style="padding: 40px 0;">
<div class="container">
<hr>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1 id="page_title">We are glad to hear from you !</h1>
			<p class="lead">Thank you for your message. We shall get back to you asap!</p>
		</div>
	</div>
<hr>
	<div class="row">
		<div class="col-md-4 pull-right">
		<%= link_to "Back to home",  root_path, class:'btn btn-warning btn-lg'%>
		</div>
	</div>
</div>
</section>
<%= render 'layouts/footer'%>
<%= render 'layouts/rights'%>

app/views/layouts/_navbar.html.erb

<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-ex1-collapse" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="/">Africarlogistics</a>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="/services">Services</a></li>
        <!-- <li class="dropdown"> -->
          <!-- <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"><i class="fa fa-angle-down"></i></a> -->
          <!-- <ul class="dropdown-menu"> -->
            <!-- <li><a href="/portfolio">1 Column Portfolio</a></li> -->
            <!--<li><a href="/portfolio">2 Column Portfolio</a></li>-->
            <!--<li><a href="/portfolio">3 Column Portfolio</a></li>-->
            <!--<li><a href="/portfolio">Single Portfolio Item</a></li>-->
          <!-- </ul> -->
        <!-- </li> -->
      <!--   <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">Blog <i class="fa fa-angle-down"></i></a>
          <ul class="dropdown-menu">
            <li><a href="/blog">Blog Home</a></li>
            <li><%= link_to "Blog Post", blog_path(:id)%></li>
            <!--<li><a href="/blog/show">Blog Post</a></li>-->
          <!-- </ul> -->
        <!-- </li> --> -->
        <li><a href="/static_pages/faq">FAQs</a></li>
          <li><%= link_to "Contact Us", new_contact_path %></li>
<!--        <li><a href="/contacts">Contact</a></li>-->
        <% if signed_in?%>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
                <li><%= link_to "Edit profile", edit_user_registration_path%></li>
              </ul>
            </li>
        <%else%>
           
           
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>


app/views/layouts/_rights.html.erb
<div class="footer-after">
  <div class="container">
    <div class="row">
      <p class="col-md-10">©2016 All rights reserved. Designed by <a href="https://www.therailsshop.club" target="_blank">TheRailsShop LTD</a></p>
<!--      <p class="col-md-2 legal"><a href="#" rel="nofollow">Legal Notice</a></p>-->
    </div><!-- /.row -->
  </div>
</div>

app/views/portfolio/index.html.erb
<%= render 'layouts/navbar'%>

<div class="section-header">
  <div class="container">
    <div class="row">

      <div class="col-lg-12">
        <h1 class="page-header">Portfolio</h1>
      </div>

    </div>
  </div> <!-- /.container -->
</div> <!-- /.section-colored -->

<div class="container container-int">

  <ol class="breadcrumb">
    <li><%= link_to "Home", root_path%></li>
    <li class="active">Portfolio</li>
  </ol>

  <div class="row">

    <div class="col-md-7 col-sm-7">
      <a href="portfolio-item.html"><img class="img-responsive" src="/assets/portfolio_1.png" alt="Portfolio 1"></a>
    </div>

    <div class="col-md-5 col-sm-5">
      <h3>Banzhow Template</h3>
      <h4>Web Design</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar quam sed consequat adipiscing.</p>
      <a class="btn btn-primary" <%= link_to "View Project", portfolio_path(:id)%> <i class="fa fa-angle-right"></i></a>
    </div>

  </div>

  <hr>

  <div class="row">

    <div class="col-md-7 col-sm-7">
      <a href="portfolio-item.html"><img class="img-responsive" src="/assets/portfolio_2.png" alt="Portfolio 2"></a>
    </div>

    <div class="col-md-5 col-sm-5">
      <h3>Banzhow Template</h3>
      <h4>Web Design</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar quam sed consequat adipiscing.</p>
      <a class="btn btn-primary" <%= link_to "View Project", portfolio_path(:id)%> <i class="fa fa-angle-right"></i></a>
    </div>

  </div>

  <hr>

  <div class="row">

    <div class="col-md-7 col-sm-7">
      <a href="portfolio-item.html"><img class="img-responsive" src="/assets/portfolio_3.png" alt="Portfolio 3"></a>
    </div>

    <div class="col-md-5 col-sm-5">
      <h3>Banzhow Template</h3>
      <h4>Web Design</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar quam sed consequat adipiscing.</p>
      <a class="btn btn-primary" <%= link_to "View Project", portfolio_path(:id)%> <i class="fa fa-angle-right"></i></a>
    </div>

  </div>

  <hr>

  <div class="row">

    <div class="col-md-7 col-sm-7">
      <a href="portfolio-item.html"><img class="img-responsive" src="/assets/portfolio_4.png" alt="Portfolio 4"></a>
    </div>

    <div class="col-md-5 col-sm-5">
      <h3>Banzhow Template</h3>
      <h4>Web Design</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar quam sed consequat adipiscing.</p>
      <a class="btn btn-primary" <%= link_to "View Project", portfolio_path(:id)%> <i class="fa fa-angle-right"></i></a>
    </div>

  </div>

  <hr>

  <div class="row">

    <div class="col-md-7 col-sm-7">
      <a href="portfolio-item.html"><img class="img-responsive" src="/assets/portfolio_5.png" alt="Portfolio 5"></a>
    </div>

    <div class="col-md-5 col-sm-5">
      <h3>Banzhow Template</h3>
      <h4>Web Design</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar quam sed consequat adipiscing.</p>
      <a class="btn btn-primary" <%= link_to "View Project", portfolio_path(:id)%> <i class="fa fa-angle-right"></i></a>
    </div>

  </div>

  <hr>

  <div class="row">

    <div class="col-md-7 col-sm-7">
      <a href="portfolio-item.html"><img class="img-responsive" src="/assets/portfolio_6.png" alt="Portfolio 6"></a>
    </div>

    <div class="col-md-5 col-sm-5">
      <h3>Banzhow Template</h3>
      <h4>Web Design</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar quam sed consequat adipiscing.</p>
      <a class="btn btn-primary" <%= link_to "View Project", portfolio_path(:id)%> <i class="fa fa-angle-right"></i></a>
    </div>

  </div>

</div><!-- /.container -->

<%= render 'layouts/footer'%>

<%= render 'layouts/rights'%>


app/views/portfolio/show.html.erb
<%= render 'layouts/navbar'%>

<div class="section-header">
  <div class="container">
    <div class="row">

      <div class="col-lg-12">
        <h1 class="page-header">Banzhow Template</h1>
      </div>

    </div>
  </div> <!-- /.container -->
</div> <!-- /.section-colored -->

<div class="container container-int">

  <ol class="breadcrumb">
    <li><%= link_to "Home", root_path%></li>
    <li><%= link_to "Portfolio", portfolio_index_path%></li>
    <li class="active">Banzhow Template</li>
  </ol>

  <div class="row">

    <div class="col-md-8">
      <img class="img-responsive" src="/assets/portfolio_1.png" alt="Portfolio 1">
    </div>

    <div class="col-md-4">
      <h3><small>Date</small></h3>
      <small>January 2014</small>
      <h3><small>Client</small></h3>
      <p><small>Banzhow</small></p>
      <h3>Description</h3>
      <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</p>

    </div>

  </div>


  <div class="row">

    <div class="col-lg-12">
      <h3 class="page-header">Related Projects</h3>
    </div>

    <div class="col-sm-3 col-xs-6">
      <a href="#" class="link-portfolio">
        <div class="overlay-portfolio">
          <h3>Banzhow Template</h3>
        </div><!-- /.overlay-portfolio -->
        <img class="img-responsive img-customer" src="/assets/portfolio_2.png" alt="Portfolio 2">
      </a>
    </div>

    <div class="col-sm-3 col-xs-6">
      <a href="#" class="link-portfolio">
        <div class="overlay-portfolio">
          <h3>Banzhow Template</h3>
        </div><!-- /.overlay-portfolio -->
        <img class="img-responsive img-customer" src="/assets/portfolio_3.png" alt="Portfolio 3">
      </a>
    </div>

    <div class="col-sm-3 col-xs-6">
      <a href="#" class="link-portfolio">
        <div class="overlay-portfolio">
          <h3>Banzhow Template</h3>
        </div><!-- /.overlay-portfolio -->
        <img class="img-responsive img-customer" src="/assets/portfolio_4.png" alt="Portfolio 4">
      </a>
    </div>

    <div class="col-sm-3 col-xs-6">
      <a href="#" class="link-portfolio">
        <div class="overlay-portfolio">
          <h3>Banzhow Template</h3>
        </div><!-- /.overlay-portfolio -->
        <img class="img-responsive img-customer" src="/assets/portfolio_5.png" alt="Portfolio 5">
      </a>
    </div>

  </div>

</div><!-- /.container -->

<%= render 'layouts/footer'%>

<%= render 'layouts/rights'%>


app/views/welcome/index.html.erb
<%= render 'layouts/navbar'%>


<div id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
   
    <div class="item">
      <div class="fill" style="background-image:url('/assets/lion.jpg');"></div>
      <div class="carousel-caption">
        <h2>african lion</h2>
         <br>
        <br>
        <%unless signed_in?%>
         <%= link_to "Register to recieve offers", new_user_registration_path, class:'btn btn-lg btn-danger'%>
         <%end%>
        <!--<a href="#" class="button">SEE MORE</a>-->
      </div>
    </div>
    <div class="item active">
      <div class="fill" style="background-image:url('/assets/jinja_nile.jpg');"></div>
      <div class="carousel-caption">
        <h2>source of the nile river</h2>
        <!--<a href="#" class="button">DOWNLOAD</a>-->
         <br>
        <br>
        <%unless signed_in?%>
          <%= link_to "Register to recieve offers", new_user_registration_path, class:'btn btn-lg btn-danger'%>
        <%end%>
        
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <i class="fa fa-angle-left"></i>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <i class="fa fa-angle-right"></i>
  </a>
</div>

<div class="section">

  <div class="container">

    <div class="row">
      <div class="col-md-4 col-sm-4">
        <div class="block-icon">
         <i class="fa fa-truck" ></i>
        </div>

        <div class="block-body">
          <h2>Car hire services</h2>
          <div class="line-subtitle"></div>
          <p>Africarlogistics offers car hire services for town and upcountry travels.We have the best cars and professional drivers.<br/><br/>
             <%= link_to "SEE MORE CAR SERVICES", services_path, class: "btn btn-danger btn-lg"%>
<!--              <a href="#" class="btn btn-lg btn-danger">SEE MORE</a>-->
          </p>
            
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <div class="block-icon">
<!--          <i class="fa fa-users"></i>-->
      <i class="fa fa-plane"></i>
        </div>

        <div class="block-body">
          <h2>International travel and Air tickets</h2>
          <div class="line-subtitle"></div>
          <p>We offer international holiday packages and Air tickets. Read more for details of what we have to offer.<br/><br/>
           <%= link_to "SEE MORE TRAVEL DETAILS", services_path, class: "btn btn-warning btn-lg"%>
<!--           <a href="#" class=" btn btn-lg btn-success">SEE MORE</a>  -->
          </p>
            
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <div class="block-icon">
          <i class="fa fa-cog"></i>
        </div>

        <div class="block-body">
          <h2>Customize your holiday with us</h2>
          <div class="line-subtitle"></div>
          <p>Let us know how you want to experience your holiday and we shall make the necessary arrangements.<br/><br/>
           <%= link_to "CONTACT US FOR DETAILS", new_contact_path, class: "btn btn-success btn-lg"%>
<!--          <a href="#" class="btn btn-lg btn-warning">SEE MORE</a>    -->
         </p>
            
        </div>
      </div>
    </div><!-- /.row -->                    

  </div><!-- /.container -->

</div><!-- /.section -->

<div class="section-colored home">

  <div class="container">

    <div class="row">
      <div class="col-md-9 col-sm-8">
        <h2>We can make your dream holiday a success!</h2>
      </div>
      <div class="col-md-3 col-sm-4">
        <%= link_to "Contact us", new_contact_path, class: "btn btn-danger btn-lg"%>
<!--        <a href="#" class="btn btn-danger btn-lg">Contact us</a>-->
      </div>
    </div><!-- /.row -->

  </div><!-- /.container -->

</div><!-- /.section-colored -->

<div class="section" id="recent-projects" style="position: relative;">

  <div class="container">

    <div class="row">
      <div class="col-lg-12">
        <h2 class="section-title">Recent tours</h2>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
<!--       <%= link_to "", services_path, class:"link-portfolio"%>-->
        <a href="#" class="link-portfolio">
          <div class="overlay-portfolio">
            <h3>Tsavo national park</h3>
            <small class="text-muted">
             
            </small>
          </div><!-- /.overlay-portfolio -->
          <img class="img-responsive img-home-portfolio" src="/assets/lions_lying.jpg" alt="portfolio 1">
        </a>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <a href="#" class="link-portfolio">
          <div class="overlay-portfolio">
            <h3>Rhino sanctuary</h3>
            <small class="text-muted">
             
            </small>
          </div><!-- /.overlay-portfolio -->
          <img class="img-responsive img-home-portfolio" src="/assets/rhino.jpg" alt="portfolio 2">
        </a>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <a href="#" class="link-portfolio">
          <div class="overlay-portfolio">
            <h3>Kidepo National park</h3>
            <small class="text-muted">
             
            </small>
          </div><!-- /.overlay-portfolio -->
          <img class="img-responsive img-home-portfolio" src="/assets/lion.jpg" alt="portfolio 3">
        </a>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <a href="#" class="link-portfolio">
          <div class="overlay-portfolio">
            <h3>Paara Lodge</h3>
            <small class="text-muted">
             
            </small>
          </div><!-- /.overlay-portfolio -->
          <img class="img-responsive img-home-portfolio" src="/assets/zebras.jpg" alt="portfolio 4">
        </a>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <a href="#" class="link-portfolio">
          <div class="overlay-portfolio">
            <h3>Enengo valley</h3>
            <small class="text-muted">
             
            </small>
          </div><!-- /.overlay-portfolio -->
          <img class="img-responsive img-home-portfolio" src="/assets/african_children.jpg" alt="portfolio 5">
        </a>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6">
        <a href="#" class="link-portfolio">
          <div class="overlay-portfolio">
            <h3>Mweya safari Lodge</h3>
            <small class="text-muted">
             
            </small>
          </div><!-- /.overlay-portfolio -->
          <img class="img-responsive img-home-portfolio" src="/assets/jinja_nile.jpg" alt="portfolio 6">
        </a>
      </div>
    </div><!-- /.row -->

  </div><!-- /.container -->

</div><!-- /.section -->

<div class="section-colored">

  <div class="container">
    <h3 class="section-title text-center">Some of Our Clients</h3>

    <div class="container clients">

      <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
          <a href="#"><img class="img-responsive" src="/assets/singapore.png" alt="client 1"></a>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
          <a href="#"><img class="img-responsive" src="/assets/turkish.png" alt="client 2"></a>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
          <a href="#"><img class="img-responsive" src="/assets/malaysia.png" alt="client 3"></a>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
          <a href="#"><img class="img-responsive" src="/assets/emirates.gif" alt="client 4"></a>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
          <a href="#"><img class="img-responsive" src="/assets/airfrance.jpg" alt="client 5"></a>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
          <a href="#"><img class="img-responsive" src="/assets/qatar.jpg" alt="client 6"></a>
        </div>
      </div><!-- /.row -->

    </div><!-- /.container -->

  </div><!-- /.container -->

</div><!-- /.section-colored -->

<%= render 'layouts/footer'%>

<%= render 'layouts/rights'%>